# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     # NOTE -> for Nginx ingress
#     # kubernetes.io/ingress.class: nginx
#     # nginx.ingress.kubernetes.io/rewrite-target: /$2
#     # NOTE -> for Traefik ingress
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/router.middlewares: ingress-stripprefix@kubernetescrd
#     ingress.kubernetes.io/ssl-redirect: "false"
#   name: blog
#   namespace: prod
# spec:
#   # ingressClassName: nginx
#   rules:
#     # - host: localhost
#     - http:
#         paths:
#           - path: /posts
#             pathType: Prefix
#             backend:
#               service:
#                 name: posts
#                 port:
#                   number: 4000
#           - path: /event-bus(/|$)(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: event-bus
#                 port:
#                   number: 4005
# ---
# #  Strip prefix /foobar and /fiibar
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /posts
#       - /event-bus
